pipeline{
     agent any
     tools{
         maven 'Maven'
         jdk 'jdk'

          }
   stages {
       stage('Git checkout')
       {
            steps{
                 script{
                 FAILED_STAGE= env.STAGE_NAME
                 git branch: 'master', url: 'https://github.com/sreelakshmi665/Trailtera.git'
                 }
            }
       }
      stage("validate"){
          steps{
               script{
               FAILED_STAGE=env.STAGE_NAME
              bat 'mvn -f codingChallenge -B -DskipTests clean validate'
               }
          }
      }
       stage("compile"){
          steps{
               script{
               FAILED_STAGE=env.STAGE_NAME
              bat 'mvn  -f codingChallenge compile'
               }
          }
      }
         stage('sonar analysis'){
            steps{
                script{
                FAILED_STAGE=env.STAGE_NAME
                withSonarQubeEnv('sonar-server'){
                    withMaven(maven:'Maven'){
                        bat 'mvn -f codingChallenge sonar:sonar'
                    }
                }
                }
            }

        }
        stage("Quality gate") {
            steps {
                script{
                     FAILED_STAGE=env.STAGE_NAME
                waitForQualityGate abortPipeline: true
                }
            }
        }
             
      stage("package"){
          steps{
               script{
               FAILED_STAGE=env.STAGE_NAME
               bat 'mvn -f codingChallenge  -B -DskipTests package -Dbuild.number=-${BUILD_NUMBER}'
               }
          }
      }
        
   stage('Collect-Artifactory')
    {
      steps{
         script{
          FAILED_STAGE=env.STAGE_NAME
              archiveArtifacts artifacts:'codingChallenge/target/*.jar',followSymlinks:false
          }
      }
    }   
    stage('Deploy-To-Artifactory')
    {
      steps{
           
         script{
              FAILED_STAGE=env.STAGE_NAME
        rtUpload(
          serverId:'artifactory-server',
          spec: '''{
          "files": [
            {
              "pattern": "codingChallenge/target/*.jar",
              "target": "art-doc-dev-loc"
            }
         ]
    }''',
          
)
          }
  }
} 
        stage('Download-To-Artifactory')
    {
      steps{
           
         script{
              FAILED_STAGE=env.STAGE_NAME
        rtDownload(
          serverId:'artifactory-server',
          spec: '''{
          "files": [
            {
              "pattern": "art-doc-dev-loc/*.jar",
              "target": "C:/Users/vscr9/.m2/repository"
            }
         ]
    }''',
          
)
          }
  }
} 
        stage("terraform")
             {
                  steps{
                       script{
                            FAILED_STAGE=env.STAGE_NAME
                             withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'b44589a1-cd4f-4f70-baa2-833d7b07e042', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
                                  bat "terraform init"
                                  bat "terraform plan"
                                    def userInput = input(id: 'confirm', message: 'Apply Terraform?', parameters: [ [$class: 'BooleanParameterDefinition', defaultValue: false, description: 'Apply terraform', name: 'confirm'] ])
                                  bat 'terraform apply -input=false'
                             }
                       }
                  }
             }
         
                            
                                  
   
        
            
   }
     post {  
         always {  
             echo 'This will always run'  
         }  
         success {  
             echo 'This will run only if successful'  
         }  
         failure {  
             mail bcc: '', body: "<b>Example</b><br>Project: ${env.JOB_NAME} <br>Build Number: ${env.BUILD_NUMBER} <br>Build Stage: ${FAILED_STAGE} <br> URL de build: ${env.BUILD_URL}", cc: '', charset: 'UTF-8', from: 'sravaninuthanapati15@gmail.com', mimeType: 'text/html', replyTo: '', subject: "ERROR CI: Project name -> ${env.JOB_NAME}", to: "sreelakshmilucky14@gmail.com";  
         }  
         unstable {  
             echo 'This will run only if  the run was marked as unstable'  
         }  
         changed {  
             echo 'This will run only if the state of the Pipeline has changed'  
             echo 'For example, if the Pipeline was previously failing but is now successful'  
         }  
     }      
}
