pipeline{
     agent any
     tools{
         maven 'Maven'
         jdk 'jdk'

          }
   stages {
       stage('Git checkout')
       {
            steps{
                 git 'https://github.com/sreelakshmi665/Trailtera.git'
            }
       }
      stage("validate"){
          steps{
              bat 'mvn -f codingChallenge -B -DskipTests clean validate'
          }
      }
       stage("compile"){
          steps{
              bat 'mvn  -f codingChallenge compile'
          }
      }
      stage("package"){
          steps{
               bat 'mvn -f codingChallenge  -B -DskipTests package '
          }
      }
   }
}
